version: '3'

services:
  compensation-service:
    build:
      context: ./compensation-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  mongodb:
    image: mongo:latest
    environment:
        MONGO_INITDB_DATABASE: employees
    ports:
      - 27017:27017
