
swagger: "2.0"
info:
  version: "1.0.0"
  title: "employees"
basePath: "/api/v1"
tags:
  - name: "employee"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /employee/{employee_id}:
    get:
      tags:
      - "employee"
      summary: "Get an employee data from database"
      operationId: "get_employee"
      parameters:
        - name: "employee_id"
          in: "path"
          description: "The id of the employee to retrieve"
          required: true
          type: "string"
        - name: "title"
          in: "header"
          description: "employees Title in company"
          required: false
          type: "string"
        - name: "Experience"
          in: "header"
          description: "employees experience in years"
          required: false
          type: "integer"
        - name: "salary"
          in: "header"
          description: "employees current salary"
          required: false
          type: "number"
      responses:
        200:
          description: "Successfully retrived employee"
          schema:
            $ref: "#/definitions/employee"
        404:
          description: "employee doesn't exist"
      x-swagger-router-controller: "web.controllers.employee_controller"
    delete:
      tags:
      - "employee"
      summary: "Remove a employee from the database"
      operationId: "remove_employee"
      parameters:
        - name: "employee_id"
          in: "path"
          description: "The id of the employee to retrieve"
          required: true
          type: "string"
        - name: "title"
          in: "header"
          description: "employees Title in company"
          required: false
          type: "string"
        - name: "company"
          in: "header"
          description: "name of the employees company"
          required: false
          type: "string"
        - name: "Experience"
          in: "header"
          description: "employees experience in years"
          required: false
          type: "integer"
        - name: "salary"
          in: "header"
          description: "employees current salary"
          required: false
          type: "number"
      responses:
        202:
          description: "Successfully deleted employee"
        404:
          description: "employee doesn't exist"
      x-swagger-router-controller: "web.controllers.employee_controller"
definitions:
  employee:
    required:
    - employee_id
    properties:
      employee_id:
        type: string
      title:
        type: string
      experience:
        type: integer
      company:
        type: string
      salary:
        type: number


...